version: "3"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80"
    environment:
      - API_ENDPOINT=localhost:10888
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "10888:10888"
    expose:
      - 10888
    volumes:
      - ./data:/app/data
      - ./tmp:/app/tmp