FROM node:20-alpine

WORKDIR /app

COPY . /app

RUN npm config set registry https://registry.npmmirror.com && \
    npm install pnpm -g && \
    pnpm install && \
    rm -rf /app/frontend

EXPOSE 10888

CMD ["pnpm", "run", "serve:backend"]