FROM node:20-alpine

WORKDIR /app

COPY . /app

RUN npm config set registry https://registry.npmmirror.com

RUN npm install pnpm -g

RUN pnpm install

RUN rm -rf /app/frontend

EXPOSE 10888

CMD ["pnpm", "run", "serve:backend"]